version: "3.7"

services:
  mongodb:
    image: mongo:6.0.6
    container_name: clean-node-api
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - clean-node-api

networks:
  clean-node-api:
